blog/urls.py

from django.urls import path
from .views import home, detail, category, author

app_name = "blog"

urlpatterns = [
    path('', home, name="home"),
    path('page/<int:page>', home, name="home"),
    path('post/<slug:slug>', detail, name="detail"),
    path('category/<slug:slug>', category, name="category"),
    path('category/<slug:slug>/page/<int:page>', category, name="category"),
    path('author/<slug:username>', author, name="author"),
    path('author/<slug:username>/page/<int:page>', author, name="author"),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from extentions.utils import jalali_convertor
from django.utils.html import format_html
from account.models import User

# tagmanagers


class PostManager(models.Manager):
    def published(self):
        return self.filter(status='p')


class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)

# Create your models here.


class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True, blank=True,
                               on_delete=models.SET_NULL, related_name='children', verbose_name='زیر دسته')
    title = models.CharField(max_length=100, verbose_name="عنوان دسته بندی")
    slug = models.SlugField(max_length=200, unique=True, verbose_name="آدرس")
    status = models.BooleanField(
        default=True, verbose_name="آیا نمایش داده شود؟")
    position = models.IntegerField(verbose_name="پوزیشن")

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering = ['parent__id', 'position']

    def __str__(self):
        return self.title
    objects = CategoryManager()


class Post(models.Model):
    STATUS_CHOICES = [
        ('d', 'پیش نویس'),
        ('p', 'منتشر شده'),
    ]
    title = models.CharField(max_length=100, verbose_name="عنوان")
    author = models.ForeignKey(
        User, null=True, on_delete=models.SET_NULL, related_name='post', verbose_name="نویسنده")
    slug = models.SlugField(max_length=200, unique=True, verbose_name="آدرس")
    category = models.ManyToManyField(
        Category, verbose_name="دسته بندی", related_name="postcat")
    short_description = models.CharField(
        max_length=200, verbose_name="توضیحات کوتاه", null=True)
    description = models.TextField(
        blank=True, null=True, verbose_name="توضیحات")
    thumbnail = models.ImageField(upload_to="imgpost", height_field=None,
                                  width_field=None, max_length=None, verbose_name="تصویر")
    publish = models.DateTimeField(
        default=timezone.now, verbose_name="زمان انتشار")
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="زمان ایجاد")
    updated = models.DateTimeField(
        auto_now=True, verbose_name="زمان بروزرسانی")
    status = models.CharField(
        max_length=1, choices=STATUS_CHOICES, verbose_name="وضعیت")
    is_special = models.BooleanField(default=False, verbose_name="مقاله ویژه")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "پست"
        verbose_name_plural = "پست ها"

    def jpublish(self):
        return jalali_convertor(self.publish)
    jpublish.short_description = "زمان انتشار"

    objects = PostManager()

    def img_tag(self):
        return format_html("<img src='{}' width=80 height=50>".format(self.thumbnail.url))
    img_tag.short_description = "تصویر"

    def category_to_str(self):
        return ", ".join([category.title for category in self.category.active()])
    category_to_str.short_description = "دسته بندی"

    def get_absolute_url(self):
        return reverse('account:home')

# slide moodels


class Slider(models.Model):
    STATUS_CHOICES = [('d', 'عدم نمایش'), ('p', 'نمایش'), ]
    title = models.CharField(max_length=100, verbose_name="عنوان")
    description = models.TextField(
        null=True, blank=True, verbose_name="توضیحات")
    btn_txt = models.CharField(
        max_length=100, null=True, blank=True, verbose_name="عنوان دکمه")
    link = models.CharField(max_length=100, verbose_name="آدرس دکمه")
    image = models.ImageField(upload_to="imgslider", verbose_name="تصویر")
    status = models.CharField(
        max_length=1, choices=STATUS_CHOICES, verbose_name="وضعیت", default='p')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "اسلایدر صفحه اصلی"
        verbose_name_plural = "اسلایدر صفحه اصلی"


class Weblog_setting(models.Model):
    about_me = models.TextField(verbose_name="درباره من")

    class Meta:
        verbose_name = "تنظیمات سایت"
        verbose_name_plural = "تنظیمات سایت"

    def __str__(self):
        return self.about_me

blog/views.py
from django.views.generic import ListView
from account.models import User
from django.shortcuts import render, get_object_or_404
from .models import Post, Category, Weblog_setting, Slider
from django.core.paginator import Paginator

# Create your views here.


def home(request, page=1):
    post_list = Post.objects.filter(status="p").order_by("-publish")
    paginator = Paginator(post_list, 4)
    posts = paginator.page(page)
    context = {
        "post": posts,
        "about": Weblog_setting.objects.all(),
        "slid": Slider.objects.filter(status="p"), }
    return render(request, "blog/home.html", context)


def category(request, slug, page=1):
    category = get_object_or_404(Category, slug=slug, status=True)
    post_list = category.postcat.published()
    paginator = Paginator(post_list, 4)
    posts = paginator.get_page(page)
    context = {
        "categorys": category,
        "post": posts,
        "about": Weblog_setting.objects.all(),
    }
    return render(request, "blog/category_list.html", context)


def author(request, username, page=1):
    author = get_object_or_404(User, username=username)
    post_list = author.post.published()
    paginator = Paginator(post_list, 4)
    posts = paginator.get_page(page)
    context = {
        "author": author,
        "post": posts,
    }
    return render(request, "blog/author_list.html", context)


def detail(request, slug ):
    context = {
        "post": get_object_or_404(Post.objects.published(), slug=slug),
        "about": Weblog_setting.objects.all(),
    }
    return render(request, "blog/detail.html", context)

templates/blog/author_list.html
{% extends 'blog/list.html' %}
{% block page_top_title %}
کاربر {{author.get_full_name}}
{% endblock page_top_title %}

{% block page_title %}
<h3 class="alert alert-primary text-center">کاربر {{author.get_full_name}} </h3>
{% endblock page_title %}
{% block previos_page %}
{% url 'blog:author' author.username post.previous_page_number%}
{% endblock previos_page %}


{% block page_title_active %}
{% url 'blog:author' author.username i %}
{% endblock page_title_active %}


{% block page_item %}

{% url 'blog:author' author.username i %}
{% endblock page_item %}


{% block next_page %}
{% url 'blog:author' author.username post.next_page_number%}
{% endblock next_page %}

templates/blog/base.html
{% load static %}
{% load base_tags %}

<!doctype html>
<html lang="fa" dir="rtl">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- sit icon -->
    <link rel="icon" href=" {% static 'blog/css/icon.png' %} ">

    <!-- font awsome -->
    <script src="https://kit.fontawesome.com/bd215512d5.js" crossorigin="anonymous"></script>


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/mystyle.css' %}">

    <title>{% title %}
        {% block title %}

        {% endblock title %}
    </title>
</head>

<body class="container-fluid" style="background-color: #f5f6fa">
    <header>

        <!-- navbar menu -->


        {% categoty_navbar %}



        <!-- end navbar menu -->

    </header>


    {% block content %}

    {% endblock content %}


    <footer class="footer" style="    margin-top: 26px; padding-top: 15px;">
        <div class="padding-10 container">
            <a href="https://www.instagram.com/m_amir_nabavi"><i class="fa fa-instagram "
                    style="font-size:xx-large ;padding-left: 7px;"></i></a>
            <a href="https://github.com/mohamadamirnabavi"><i class="fa fa-github "
                    style="font-size:xx-large ;padding-left: 7px;"></i></a>
            <a href="https://t.me/M_amir_nn"><i class="fa fa-telegram "
                    style="font-size:xx-large ;padding-left: 7px;"></i></a>
        </div>
        <div>
            <h5 style="padding-bottom: 30px; background-color: black;">
                Created By
                <a href=" {% url 'blog:home' %} " class="footer__text" target="_blank" rel="noopener">Amir313.ir</a>
                &copy; 2021
            </h5>
        </div>
    </footer>

    <!-- Optional JavaScript -->
    <script src="{% static '/blog/js/main.js' %}"></script>

</body>

</html>

templates/blog/category_list.html
{% extends 'blog/list.html' %}
{% block page_top_title %}
{{categorys.title}}
{% endblock page_top_title %}

{% block page_title %}
<h3 class="alert alert-primary text-center"> {{categorys.title}} </h3>
{% endblock page_title %}

{% block previos_page %}
{% url 'blog:category' categorys.slug post.previous_page_number%}
{% endblock previos_page %}


{% block page_title_active %}
{% url 'blog:category' categorys.slug i %}
{% endblock page_title_active %}


{% block page_item %}
{% url 'blog:category' categorys.slug i %}
{% endblock page_item %}


{% block next_page %}
{% url 'blog:category' categorys.slug post.next_page_number%}
{% endblock next_page %}

templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block title %}
| {{post.title}}
{% endblock title %}

{% block content %}


<main class="container">

    <!-- post detail -->
    <div class="row">
        <div class="col-12 col-md-8">

            <article class="blog-post">
                <h2 class="blog-post-title">{{post.title}}</h2>
                <p class="blog-post-meta"> {{post.jpublish}} </p>
                <div class="text-center" style="padding-bottom: 30px;">
                    <img class="text-end" src=" {{post.thumbnail.url}} " width="230" alt=" {{post.title}} ">
                </div>
                <p class="col-auto d-none d-lg-block"> {{post.short_description|truncatewords:50}} </p>
                <hr>
                <p> {{post.description| safe|linebreaks}} </p>
                <div class="text-center">
                    <a href="{% url 'blog:author' post.author.username %}">نویسنده:
                    {{post.author.get_full_name }}</a>
                </div>
            </article><!-- /.blog-post -->




        </div>
        <div class="col-12 col-md-4">
            <!-- about me -->
            <div class="bg-light box-border">
                <h3 class="bg-dark text-white text-center ">درباره من</h3>
                <div class="mb-0 padding-10" style="text-align: justify;">

                    {% for abouts in about %}

                    {{abouts.about_me|linebreaks|truncatewords:50}}
                    {% endfor %}

                </div>
            </div>

            <!-- aparat video -->
            <div class="box-border bg-dark" style="margin-top: 16px;">
                <h3 class="text-center" style="color: #fff;">آخرین ویدئو آپارات من</h3>
                <style>
                    .h_iframe-aparat_embed_frame {
                        position: relative;
                    }

                    .h_iframe-aparat_embed_frame .ratio {
                        display: block;
                        width: 100%;
                        height: auto;
                    }

                    .h_iframe-aparat_embed_frame iframe {
                        position: absolute;
                        top: 0;
                        left: 0;
                        width: 100%;
                        height: 100%;
                    }
                </style>
                <div class="h_iframe-aparat_embed_frame"><span style="display: block;padding-top: 57%"></span><iframe
                        src="https://www.aparat.com/video/video/embed/videohash/0pYc3/vt/frame"
                        title="زيرنويس فارسي يوتويوب" allowFullScreen="true" webkitallowfullscreen="true"
                        mozallowfullscreen="true"></iframe></div>
            </div>

            <!-- aparat live -->
            <div class=" bg-dark" style="margin-top: 16px;">
                <div class="box-border">
                    <h3 class="text-center text-white">پخش زنده آپارات</h3>
                    <style>
                        .h_iframe-aparat_embed_frame {
                            position: relative;
                        }

                        .h_iframe-aparat_embed_frame .ratio {
                            display: block;
                            width: 100%;
                            height: auto;
                        }

                        .h_iframe-aparat_embed_frame iframe {
                            position: absolute;
                            top: 0;
                            left: 0;
                            width: 100%;
                            height: 100%;
                        }
                    </style>
                    <div class="h_iframe-aparat_embed_frame"> <span
                            style="display: block;padding-top: 57%"></span><iframe scrolling="no" allowFullScreen="true"
                            webkitallowfullscreen="true" mozallowfullscreen="true"
                            src="https://www.aparat.com/embed/live/amirnabavi.ir"></iframe></div>
                </div>
            </div>
            <!-- archive -->

            <div class=" bg-light box-border" style="margin-top: 16px;">
                <h3 class="bg-dark text-white text-center">آرشیو مطالب</h3>
                <div class="padding-10">
                    <ol class="list-unstyled mb-0">
                        <li><a class="a_text" href="#">فروردین ۱۴۰۰</a></li>

                    </ol>
                </div>
            </div>

        </div>
    </div>


    </div>

</main>

{% endblock content %}

templates/blog/home.html
{% extends 'blog/list.html' %}

{% block page_top_title %}
صفحه اصلی
{% endblock page_top_title %}


{% block carousel %}
<!-- carousel -->
<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <ol class="carousel-indicators">
        <li data-bs-target="#myCarousel" data-bs-slide-to="0" class=""></li>
        <li data-bs-target="#myCarousel" data-bs-slide-to="1" class="active"></li>
        <li data-bs-target="#myCarousel" data-bs-slide-to="2" class=""></li>
    </ol>

    <div class="carousel-inner">
        {% for slids in slid  %}
        <div class="carousel-item item{% if forloop.first %} active{% endif %}">
            <img src=" {{slids.image.url}} " alt="{{slids.title}}">

            <div class="container">
                <div class="carousel-caption text-start">
                    <h2>{{slids.title}}</h2>
                    </h2>
                    <p>{{slids.description|truncatewords:30}}</p>
                    </p>
                    <p><a class="btn btn-lg btn-blue" href="{{slids.link}} " role="button">{{slids.btn_txt}} </a>
                    </p>
                </div>
            </div>
        </div>

        {% endfor %}


    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon"></span>
        <span class="visually-hidden">قبلی</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon"></span>
        <span class="visually-hidden">بعدی</span>
    </a>
</div>
<!-- end carousel -->
{% endblock carousel %}


{% block page_title %}
<h3 class="alert alert-primary text-center"> صفحه اصلی </h3>
{% endblock page_title %}


{% block previos_page %}
{% url 'blog:home' post.previous_page_number  %}
{% endblock previos_page %}


{% block page_title_active %}
{% url 'blog:home' i %}
{% endblock page_title_active %}


{% block page_item %}
{% url 'blog:home' i %}
{% endblock page_item %}


{% block next_page %}
{% url 'blog:home' post.next_page_number %}
{% endblock next_page %}

templates/blog/list.html
{% extends 'blog/base.html' %}

{% block title %}
|
{% block page_top_title %}

{% endblock page_top_title %}

{% endblock title %}


{% block content %}
<main class="container">


{% block carousel %}

{% endblock carousel %}

    <!-- content -->

    <div class="row" style="padding-top: 15px;">
        <div class="col-12 col-md-8">

            {% block page_title %}

            {% endblock page_title %}

            {% for posts in post  %}

            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col-auto d-none d-lg-block">
                    <!-- <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg"
                        role="img" preserveAspectRatio="xMidYMid slice" focusable="false">
                        <title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef"
                            dy=".3em">عکس پست</text>
                    </svg> -->
                    <img src="{{posts.thumbnail.url}}" width="200"height="200" alt="">
                </div>

                <div class="col p-4 d-flex flex-column position-static">
                    <h3> <strong class="d-inline-block mb-2 text-primary"> {{posts.title}} </strong></h3>
                    <div class="mb-1 text-muted"> {{posts.jpublish}} </a></div>
                    <p class="card-text mb-auto ">
                        {{posts.short_description|linebreaks|truncatewords:58}}
                    </p>
                    <a href=" {% url 'blog:detail' posts.slug %}" class="stretched-link a_text">مطالعه بیشتر</a>
                </div>

            </div>
            {% endfor %}





            <div class="container ">

                {% if post.has_other_pages %}
                <nav>
                    <ul class="pagination justify-content-center">
                        {% if post.has_previous %}
                        <li class="page-item"><a class="page-link" href="{% block previos_page %}{% endblock previos_page %} ">&laquo;</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled"></li>
                        {% endif %}

                        {% for i in post.paginator.page_range %}
                        {% if post.number == i %}

                        <li class="page-item active" aria-current="page"><a class="page-link" href="{% block page_title_active %} {% endblock page_title_active %}">{{ i }}</a></li>
                        {% else %}
                        <li class="page-item"><a class="page-link" href=" {% block page_item %}{% endblock page_item %}">{{ i }}</a></li>
                        {% endif %}

                        {% endfor %}

                        {% if post.has_next %}
                        <li class="page-item"><a class="page-link" href="{% block next_page %}{% endblock next_page %}">&raquo;</a>
                        </li>
                        {% else %}
                        <li class="disabled page-item"></li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}
            </div>



        </div>

        <div class="col-12 col-md-4">
            <!-- about me -->
            {% for abouts in about  %}
            <div class="bg-light box-border">
                <h3 class="bg-dark text-white text-center ">درباره من</h3>
                <div class="mb-0 padding-10" style="text-align: justify;">
                    {{abouts.about_me|linebreaks|truncatewords:50}}
                </div>
            </div>
            {% endfor %}

            <!-- aparat video -->
            <div class="box-border bg-dark" style="margin-top: 16px;">
                <h3 class="text-center" style="color: #fff;">آخرین ویدئو آپارات من</h3>
                <style>
                    .h_iframe-aparat_embed_frame {
                        position: relative;
                    }

                    .h_iframe-aparat_embed_frame .ratio {
                        display: block;
                        width: 100%;
                        height: auto;
                    }

                    .h_iframe-aparat_embed_frame iframe {
                        position: absolute;
                        top: 0;
                        left: 0;
                        width: 100%;
                        height: 100%;
                    }
                </style>
                <div class="h_iframe-aparat_embed_frame"><span style="display: block;padding-top: 57%"></span><iframe
                        src="https://www.aparat.com/video/video/embed/videohash/0pYc3/vt/frame"
                        title="زيرنويس فارسي يوتويوب" allowFullScreen="true" webkitallowfullscreen="true"
                        mozallowfullscreen="true"></iframe></div>
            </div>

            <!-- aparat live -->
            <div class=" bg-dark" style="margin-top: 16px;">
                <div class="box-border">
                    <h3 class="text-center text-white">پخش زنده آپارات</h3>
                    <style>
                        .h_iframe-aparat_embed_frame {
                            position: relative;
                        }

                        .h_iframe-aparat_embed_frame .ratio {
                            display: block;
                            width: 100%;
                            height: auto;
                        }

                        .h_iframe-aparat_embed_frame iframe {
                            position: absolute;
                            top: 0;
                            left: 0;
                            width: 100%;
                            height: 100%;
                        }
                    </style>
                    <div class="h_iframe-aparat_embed_frame"> <span
                            style="display: block;padding-top: 57%"></span><iframe scrolling="no" allowFullScreen="true"
                            webkitallowfullscreen="true" mozallowfullscreen="true"
                            src="https://www.aparat.com/embed/live/amirnabavi.ir"></iframe></div>
                </div>
            </div>
            <!-- archive -->
            <div class=" bg-light box-border" style="margin-top: 16px;">
                <h3 class="bg-dark text-white text-center">آرشیو مطالب</h3>
                <div class="padding-10">
                    <ol class="list-unstyled mb-0">
                        <li><a class="a_text" href="#">فروردین ۱۴۰۰</a></li>

                    </ol>
                </div>
            </div>

        </div>
    </div>

    <!-- end content -->

</main>
{% endblock content %}